Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -1,9 +1,9 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: BOTSSH SSHPLUS MANAGER
-#	DESENVOLVIDO POR:	CRAZY_VPN
-#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
-#	CANAL TELEGRAM:	http://t.me/sshplus
+#   SCRIPT: BOTSSH SSHPLUS MANAGER
+#   DEVELOPED BY: CRAZY_VPN
+#   CONTACT TELEGRAM: http://t.me/crazy_vpn
+#   TELEGRAM CHANNEL: http://t.me/sshplus
 #====================================================
 clear
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) != "@CRAZY_VPN" ]] && exit 0
@@ -30,25 +30,25 @@ fun_bar() {
         tput dl1
         echo -ne "\033[1;33m["
     done
-    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
+    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK!\033[1;37m"
     tput cnorm
 }
 
 fun_botOnOff() {
     [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) = '0' ]] && {
         clear
-        echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-        echo -ne "\033[1;32mINFORME SEU TOKEN:\033[1;37m "
+        echo -e "\E[44;1;37m             SSHPLUS BOT INSTALLER                \E[0m\n"
+        echo -ne "\033[1;32mENTER YOUR TOKEN:\033[1;37m "
         read tokenbot
         echo ""
-        echo -ne "\033[1;32mINFORME SEU ID:\033[1;37m "
+        echo -ne "\033[1;32mENTER YOUR ID:\033[1;37m "
         read iduser
         clear
-        echo -e "\033[1;32mINICIANDO BOT SSHPLUS \033[0m\n"
+        echo -e "\033[1;32mSTARTING SSHPLUS BOT \033[0m\n"
         fun_bot1() {
             [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && {
-				wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh >/etc/SSHPlus/ShellBot.sh
-			}
+                wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh >/etc/SSHPlus/ShellBot.sh
+            }
             cd /etc/SSHPlus
             screen -dmS bot_plus ./bot $tokenbot $iduser >/dev/null 2>&1
             [[ $(grep -wc "bot_plus" /etc/autostart) = '0' ]] && {
@@ -64,12 +64,12 @@ fun_botOnOff() {
             cd $HOME
         }
         fun_bar 'fun_bot1'
-        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT SSHPLUS ATIVADO !\033[0m" || echo -e "\n\033[1;31m ERRO! REANALISE SUAS INFORMACOES\033[0m"
+        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m SSHPLUS BOT ACTIVATED!\033[0m" || echo -e "\n\033[1;31m ERROR! CHECK YOUR INFORMATION\033[0m"
         sleep 2
         menu
     } || {
         clear
-        echo -e "\033[1;32mPARANDO BOT SSHPLUS... \033[0m\n"
+        echo -e "\033[1;32mSTOPPING SSHPLUS BOT... \033[0m\n"
         fun_bot2() {
             screen -r -S "bot_plus" -X quit
             screen -wipe 1>/dev/null 2>/dev/null
@@ -80,28 +80,28 @@ fun_botOnOff() {
             sleep 1
         }
         fun_bar 'fun_bot2'
-        echo -e "\n\033[1;32m \033[1;31mBOT SSHPLUS PARADO! \033[0m"
+        echo -e "\n\033[1;32m \033[1;31mSSHPLUS BOT STOPPED! \033[0m"
         sleep 2
         menu
     }
 }
 
 fun_instbot() {
-    echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCAO \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mPELO SEU TELEGRAM ACESSE OS SEGUINTES BOT\033[1;37m:\033[0m"
-    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCRIE O SEU BOT \033[1;31mOPCAO: \033[1;37m/newbot\033[0m"
-    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@SSHPLUS_BOT \033[1;33mE PEGUE SEU ID \033[1;31mOPCAO: \033[1;37m/id\033[0m"
+    echo -e "\E[44;1;37m             SSHPLUS BOT INSTALLER                \E[0m\n"
+    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATTENTION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mUSE YOUR TELEGRAM TO ACCESS THE FOLLOWING BOTS\033[1;37m:\033[0m"
+    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREATE YOUR BOT \033[1;31mOPTION: \033[1;37m/newbot\033[0m"
+    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@SSHPLUS_BOT \033[1;33mTO GET YOUR ID \033[1;31mOPTION: \033[1;37m/id\033[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
     echo ""
-    read -p "DESEJA CONTINUAR ? [s/n]: " -e -i s resposta
-    [[ "$resposta" = 's' ]] && {
+    read -p "DO YOU WANT TO CONTINUE? [y/n]: " -e -i y answer
+    [[ "$answer" = 'y' ]] && {
         fun_botOnOff
     } || {
-        echo -e "\n\033[1;31mRetornando...\033[0m"
+        echo -e "\n\033[1;31mReturning...\033[0m"
         sleep 2
         menu
     }
 }
 [[ -f "/etc/SSHPlus/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
-#fim
+#end
